version: '3.9'
services:
  frontend:
    container_name: app-front-end
    build: ./front-end
    ports:
      - 3070:3000
    platform: linux/x86_64
    working_dir: /app-front-end
    volumes:
      - ./front-end:/app-front-end
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3070']
      timeout: 10s
      retries: 5
  backend:
    container_name: app-back-end
    build: ./back-end
    ports:
      - 3071:3071
    platform: linux/x86_64
    working_dir: /app-back-end
    volumes:
      - ./back-end:/app-back-end
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3071
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3071']
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: app-db
    platform: linux/x86_64
    ports:
      - 3072:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
