#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff-index --cached --exit-code HEAD -- "front-end"; then
  echo "- - - - - - - - - - - - - -\nNo changes in the front-end\n- - - - - - - - - - - - - -"
else
  echo "- - - - - - - - - - - - - - - - -\nChecking changes in the front-end\n- - - - - - - - - - - - - - - - -"
  (cd "front-end" && npx lint-staged --concurrent false)
fi

if git diff-index --cached --exit-code HEAD -- "back-end"; then
  echo "- - - - - - - - - - - - - -\nNo changes in the back-end\n- - - - - - - - - - - - - -"
else
  echo "- - - - - - - - - - - - - - - - -\nChecking changes in the back-end\n- - - - - - - - - - - - - - - - -"
  (cd "back-end" && npx lint-staged --concurrent false)
fi
